baseURL = "https://xieby1.github.io/"
title = "xieby1🐭"
theme = "hugo-book"
uglyURLs = true
# refer to: https://github.com/gohugoio/hugo/issues/7182
relativeURLs = true
canonifyURLs = true
disablePathToLower = true

# enable iframe
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[menu]
[[menu.after]]
    name = "Github: xieby1"
    url = "https://github.com/xieby1"

[params]
    BookSection = '*'
